# Generated by Django 6.0.1 on 2026-02-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='employee_code',
            field=models.CharField(blank=True, help_text='Unique employee identifier', max_length=50, null=True, unique=True),
        ),
    ]
