# Generated by Django 6.0.2 on 2026-02-05 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_user_employee_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approver',
            field=models.ForeignKey(blank=True, help_text='Direct approver for leave requests. Cross-entity approval supported.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL),
        ),
    ]
