# Generated by Django 6.0.2 on 2026-02-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_approver_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_login',
            field=models.BooleanField(default=True, help_text='Flag to force password change on first login'),
        ),
    ]
