# Generated by Django 6.0.5 on 2026-06-06 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='final_approver',
            field=models.ForeignKey(blank=True, help_text='Optional final approver for two-step leave approval.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_approval_subordinates', to=settings.AUTH_USER_MODEL),
        ),
    ]
