# Generated by Django 6.0.5 on 2026-06-10 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_workshift'),
        ('users', '0007_rename_user_approver_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organizations.workshift'),
        ),
    ]
