# Generated by Codex on 2026-06-12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='work_shift',
        ),
    ]
