# Generated by Django 6.0.5 on 2026-06-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shift_cycle_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
