# Generated by Django 6.0.5 on 2026-06-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_auditlog_action_alter_auditlog_entity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='body_html',
            field=models.TextField(blank=True),
        ),
    ]
