# Generated by Django 6.0.5 on 2026-06-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_announcement_body_html_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['starts_at', 'expires_at'], name='announcemen_starts__4d61bf_idx'),
        ),
    ]
