# Generated by Django 6.0.5 on 2026-06-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_announcement_expires_at_announcement_starts_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(choices=[('LeaveRequest', 'Leave Request'), ('User', 'User'), ('LeaveBalance', 'Leave Balance'), ('Entity', 'Entity'), ('Location', 'Location'), ('Department', 'Department')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('LEAVE_APPROVED', 'Leave Approved'), ('LEAVE_PENDING', 'Leave Pending'), ('LEAVE_REJECTED', 'Leave Rejected'), ('LEAVE_CANCELLED', 'Leave Cancelled'), ('BALANCE_LOW', 'Balance Low')], max_length=50),
        ),
    ]
