# Generated by Django 6.0.5 on 2026-06-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sync_auditlog_notification_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('GENERATE', 'Generate'), ('PUBLISH', 'Publish'), ('UNPUBLISH', 'Unpublish'), ('SPLIT_SCOPE', 'Split Scope')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(choices=[('LeaveRequest', 'Leave Request'), ('User', 'User'), ('LeaveBalance', 'Leave Balance'), ('Entity', 'Entity'), ('Location', 'Location'), ('Department', 'Department'), ('HolidayCalendar', 'Holiday Calendar'), ('PublicHoliday', 'Public Holiday')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('LEAVE_APPROVED', 'Leave Approved'), ('LEAVE_PENDING', 'Leave Pending'), ('LEAVE_REJECTED', 'Leave Rejected'), ('LEAVE_CANCELLED', 'Leave Cancelled'), ('BALANCE_LOW', 'Balance Low'), ('LEAVE_HOURS_RECALCULATED', 'Leave Hours Recalculated'), ('HOLIDAY_CALENDAR_UPDATED', 'Holiday Calendar Updated')], max_length=50),
        ),
    ]
