# Generated by Django 6.0.5 on 2026-06-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_auditlog_action_alter_auditlog_entity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(choices=[('LeaveRequest', 'Leave Request'), ('User', 'User'), ('LeaveBalance', 'Leave Balance'), ('Entity', 'Entity'), ('Location', 'Location'), ('Department', 'Department'), ('HolidayCalendar', 'Holiday Calendar'), ('PublicHoliday', 'Public Holiday'), ('APIRequest', 'API Request')], max_length=50),
        ),
    ]
