# Generated by Django 6.0.6 on 2026-07-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_auditlog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(choices=[('LeaveRequest', 'Leave Request'), ('BusinessTrip', 'Business Trip'), ('User', 'User'), ('LeaveBalance', 'Leave Balance'), ('Entity', 'Entity'), ('Location', 'Location'), ('Department', 'Department'), ('HolidayCalendar', 'Holiday Calendar'), ('PublicHoliday', 'Public Holiday'), ('APIRequest', 'API Request')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('LEAVE_APPROVED', 'Leave Approved'), ('LEAVE_PENDING', 'Leave Pending'), ('LEAVE_REJECTED', 'Leave Rejected'), ('LEAVE_CANCELLED', 'Leave Cancelled'), ('LEAVE_UPDATED', 'Leave Updated'), ('BALANCE_LOW', 'Balance Low'), ('LEAVE_HOURS_RECALCULATED', 'Leave Hours Recalculated'), ('HOLIDAY_CALENDAR_UPDATED', 'Holiday Calendar Updated')], max_length=50),
        ),
    ]
