# Generated by Django 6.0.1 on 2026-01-20 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentmanager',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organizations.entity'),
        ),
        migrations.AddField(
            model_name='location',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='organizations.entity'),
        ),
        migrations.AddField(
            model_name='departmentmanager',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.location'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('entity', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('entity', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='departmentmanager',
            unique_together={('department', 'location', 'manager')},
        ),
    ]
