# Generated by Django 6.0.1 on 2026-01-20 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_entity_from_department(apps, schema_editor):
    """Populate entity field from department.entity for existing records"""
    DepartmentManager = apps.get_model('organizations', 'DepartmentManager')
    for dm in DepartmentManager.objects.filter(entity__isnull=True):
        dm.entity = dm.department.entity
        dm.save(update_fields=['entity'])


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departmentmanager',
            unique_together={('department', 'location', 'manager')},
        ),
        migrations.AddField(
            model_name='departmentmanager',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.entity'),
        ),
        migrations.RunPython(populate_entity_from_department, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='departmentmanager',
            unique_together={('department', 'location', 'manager'), ('entity', 'department', 'location', 'manager')},
        ),
    ]
