# Generated by Django 6.0.1 on 2026-01-30 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_add_timezone_choices'),
    ]

    operations = [
        migrations.RenameField('entity', 'name', 'entity_name'),
        migrations.RenameField('location', 'name', 'location_name'),
        migrations.RenameField('department', 'name', 'department_name'),
    ]
