# Generated by Django 6.0.1 on 2026-01-31 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_rename_name_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedImportPlaceholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Organization Import',
                'verbose_name_plural': 'Organization Import',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='departmentmanager',
            options={'verbose_name_plural': 'department managers'},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('entity', 'code')},
        ),
        migrations.AddField(
            model_name='department',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organizations.location'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('entity', 'code'), ('location', 'code')},
        ),
    ]
