# Generated by Django 6.0.1 on 2026-01-31 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_unifiedimportplaceholder_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('entity', 'location', 'code')},
        ),
    ]
