# Generated by Django 6.0.2 on 2026-02-23 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_alter_department_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentManager',
        ),
    ]
