# Generated by Django 6.0.5 on 2026-06-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_remove_department_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='holiday_requires_leave',
            field=models.BooleanField(default=False, help_text='Employees must submit leave requests for published holidays.'),
        ),
    ]
