# Generated by Django 6.0.5 on 2026-06-10 22:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_department_holiday_requires_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_shifts', to='organizations.department')),
            ],
            options={
                'db_table': 'work_shifts',
                'ordering': ['department', 'start_time'],
                'unique_together': {('department', 'name')},
            },
        ),
    ]
