# Generated by Django 6.0.6 on 2026-06-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_workshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='includes_weekends',
            field=models.BooleanField(default=False, help_text='All 7 days count as deductible working days for this shift.'),
        ),
    ]
