# Generated by Django 6.0.5 on 2026-06-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_workshift_includes_weekends'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='cycle_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workshift',
            name='pattern_type',
            field=models.CharField(choices=[('FIXED_WEEKLY', 'Fixed weekly'), ('ROTATING_CYCLE', 'Rotating cycle')], default='FIXED_WEEKLY', max_length=20),
        ),
    ]
