# Generated by Codex on 2026-06-12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_work_shift'),
        ('organizations', '0011_workshift_includes_weekends'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkShift',
        ),
    ]
