# Generated by Django 6.0.1 on 2026-01-30 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_initial'),
    ]

    operations = [
        migrations.RenameField('leavecategory', 'name', 'category_name'),
        migrations.RenameField('publicholiday', 'name', 'holiday_name'),
    ]
