# Generated by Django 6.0.1 on 2026-01-30 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_rename_name_fields'),
    ]

    operations = [
        migrations.RemoveField('leavecategory', 'color'),
    ]
