# Generated by Django 6.0.1 on 2026-01-30 06:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_remove_color_from_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='request_type',
            field=models.CharField(choices=[('LEAVE', 'Leave'), ('BUSINESS_TRIP', 'Business Trip')], default='LEAVE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['request_type', 'status'], name='leave_reque_request_d62f59_idx'),
        ),
    ]
