# Generated by Django 6.0.1 on 2026-02-01 21:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def migrate_business_trips(apps, schema_editor):
    """Copy existing business trips from LeaveRequest to BusinessTrip"""
    LeaveRequest = apps.get_model('leaves', 'LeaveRequest')
    BusinessTrip = apps.get_model('leaves', 'BusinessTrip')

    # Note: Since request_type was already removed from LeaveRequest model,
    # we can't query by request_type. If there were existing business trips,
    # they would need to be migrated from a backup or manually.
    # This is a placeholder for future data migration if needed.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0005_add_request_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTrip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('attachment_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'business_trips',
            },
        ),
        migrations.RemoveIndex(
            model_name='leaverequest',
            name='leave_reque_request_d62f59_idx',
        ),
        migrations.AddField(
            model_name='businesstrip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(migrate_business_trips, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='leaverequest',
            name='request_type',
        ),
        migrations.AddIndex(
            model_name='businesstrip',
            index=models.Index(fields=['user', 'start_date'], name='business_tr_user_id_308a46_idx'),
        ),
        migrations.AddIndex(
            model_name='businesstrip',
            index=models.Index(fields=['start_date', 'end_date'], name='business_tr_start_d_a98009_idx'),
        ),
    ]
