# Generated by Django 6.0.1 on 2026-02-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0006_businesstrip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstrip',
            name='attachment_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='attachment_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
