# Generated by Django 6.0.2 on 2026-02-05 20:17

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0008_holiday_date_range'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavebalance',
            options={'ordering': ['user', 'year', 'balance_type']},
        ),
        migrations.RenameIndex(
            model_name='publicholiday',
            new_name='public_holi_start_d_ab6178_idx',
            old_name='leaves_holiday_date_idx',
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='balance_type',
            field=models.CharField(choices=[('EXEMPT_VACATION', 'Exempt Vacation'), ('NON_EXEMPT_VACATION', 'Non-Exempt Vacation'), ('EXEMPT_SICK', 'Exempt Sick Leave'), ('NON_EXEMPT_SICK', 'Non-Exempt Sick Leave')], default='EXEMPT_VACATION', max_length=30),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='exempt_type',
            field=models.CharField(choices=[('EXEMPT', 'Exempt'), ('NON_EXEMPT', 'Non-Exempt')], default='EXEMPT', max_length=20),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='allocated_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('user', 'year', 'balance_type')},
        ),
    ]
