# Generated by Django 6.0.1 on 2026-02-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0009_add_balance_type_and_exempt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstrip',
            name='attachment_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='attachment_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
