# Generated by Django 6.0.5 on 2026-06-10 15:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0014_merge_leave_balances'),
        ('organizations', '0008_remove_department_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicholiday',
            name='holiday_type',
            field=models.CharField(choices=[('STATUTORY', 'Statutory'), ('OBSERVED', 'Observed'), ('COMPENSATORY', 'Compensatory'), ('COMPANY', 'Company')], default='STATUTORY', max_length=20),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_holidays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='source_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=20),
        ),
        migrations.AlterField(
            model_name='publicholiday',
            name='holiday_name',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('country_code', models.CharField(max_length=2)),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_calendars', to='organizations.entity')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holiday_calendars', to='organizations.location')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_holiday_calendars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'holiday_calendars',
                'ordering': ['-year', 'country_code', 'name'],
            },
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='leaves.holidaycalendar'),
        ),
        migrations.CreateModel(
            name='HolidayTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=2)),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=120)),
                ('source_name', models.CharField(max_length=200)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'holiday_templates',
                'ordering': ['country_code', 'year'],
                'unique_together': {('country_code', 'year', 'version')},
            },
        ),
        migrations.AddField(
            model_name='holidaycalendar',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendars', to='leaves.holidaytemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='holidaycalendar',
            unique_together={('year', 'entity', 'location', 'country_code')},
        ),
        migrations.CreateModel(
            name='HolidayTemplateDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('holiday_name', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('holiday_type', models.CharField(choices=[('STATUTORY', 'Statutory'), ('OBSERVED', 'Observed'), ('COMPENSATORY', 'Compensatory')], default='STATUTORY', max_length=20)),
                ('source_note', models.TextField(blank=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='leaves.holidaytemplate')),
            ],
            options={
                'db_table': 'holiday_template_dates',
                'ordering': ['start_date'],
                'unique_together': {('template', 'start_date', 'holiday_name')},
            },
        ),
    ]
