# Generated by Django 6.0.5 on 2026-06-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0015_publicholiday_holiday_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='end_day_offset',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='start_day_offset',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
