# Generated by Django 6.0.5 on 2026-06-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0017_leaverequest_balance_type_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_breakdown',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
